# Jekyll Configuration
title: Karan's Digital Space
description: A diverse collection of content ranging from my professional resume to my thoughts on data science and engineering, business insights, fitness tips, and my musings on music and arts.
baseurl: ""
url: "https://karanb23.github.io"

# Build settings
theme: minima
minima:
  skin: auto

# Navigation
header_pages:
  - about.md
  - blogs.md
  - notes.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
